- _layouts/base.html
- package.json
- Build and clean the JS properly
- Remove sourcemaps from minified css
- Use the minified CSS which saves 40%~ (100KB)
- Run `./run clean` then `./run`
- Check the site is ok
- Cancel the run and run `./run` again and check it builds ok with js build step
> Improve performance

- index.html
- Avoids assuming that a non-Ubuntu user hasn’t previously installed `snapd` for some other snap.
- Avoids using the term “snapcraft”, since you don’t need to use Snapcraft to install anything.
> Simplifies installation text

- index.html
Inject the asciinema assets via JS based on the screen width 
- Load the demo
- Open you console on the network tab
- Refresh above 640px wide
- Check that the asciinema section at the bottom of the page loads
- Check the network tab shows the asciinema scripts/fonts load (~600kb combined)
- Shrink the screen below 640px and reload
- Check the section is gone
- Check there is no assets loaded in the console reducing the page load to less then a MB
Fixes https://github.com/canonical-websites/microk8s.io/issues/34
> Remove the asciinema section on small screens

- docs/working.md
Images tagged with latest are not cached by containerd, so "latest" will not work for working with containerd and no registry.
> Replace latest tag with local

- index.html
improved the layout of the features list
- go to the homepage
- scroll to the features list
- make sure it looks like this on desktop:
- make sure it looks ok on different screen sizes
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/108
> microk8s homepage - improve the ticked list design

- _layouts/base.html
- index.html
- Updated the text
- Added GitHub buttons
- Download and run this branch
- Look at the site http://0.0.0.0:8027
- See that the text matches the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
- I used the same windows and macos logos as mutlipass.run
- I guessed a design for the github buttons until @anasereijo has time
- Please accept comments in the copy doc
Fixes #110
> Update text, add GitHub buttons

- docs/clustering.md
This PR adds documentation on the clustering feature. This feature should go live with the 1.16 release planned for Sept 17.
@tvansteenburgh, lets see if this aligns with what we have planned.
> [microk8s documentation] Documentation on clustering available with the 1.16 release

- _layouts/base.html
- Reordered head tags according to Harry R's best practice guidelines
- See that the head tags are in an order that complies with this list:
```
<meta charset
<meta name=”viewport”
<meta https-equiv=”Accept-CH” content=”DPR, Viewport-Width, Width”>
<title
<preconnect / dns-prefetch
<script> inline
<link rel=”stylesheet”
<styles>Inline styles
Preload - chrome bug - makes it too important - perhaps don’t use it
<script src=”” - external scripts
prefetch/prerender
All the rest - icons, opengraph, etc..
```
> reorder head tags

- _layouts/base.html
- docs/clustering.md
- docs/ports.md
- docs/release-channels.md
- docs/working.md
- index.html
- Set permalink frontmatter for pages within `/docs` directory, to prevent a redirect
- The same didn't seem to be possible for `/docs/index.html` (open to suggestions if there's a way), so changed links to `/docs` to `/docs/`
- Visit http://0.0.0.0:8027/
- Open the network panel in dev tools
- Click "docs" in the top nav, and see that you are taken to `/docs/` without a 301 redirect
- On the docs page, click any of the links in the side nav and see that you are taken to the target page without a 301 redirect
> remove trailing slashes from /docs/ sub pages

- _layouts/docs.html
This creates a link to the clustering documentation on the left side index.
> Link to clustering

- _layouts/base.html
Added `'siteSpeedSampleRate': 100` to GA tag
## QA
- Visit http://0.0.0.0:8027
- Inspect the page source, and see that `'siteSpeedSampleRate': 100` is present in the GA tag
> increase site speed analytics sampling

- index.html
- Remove capital letter from `snap info microk8s` command
- Visit http://0.0.0.0:8027/
- Make sure there are no capital letters in the `snap info microk8s`
- Fixes #122
> Remove capital letter from command

- _sass/styles.scss
- index.html
- Added KubeCon'19 banner to homepage
- Run the site
- See that there is a banner per the [brief](https://docs.google.com/document/d/163wevrv2xmezH8PEmbRZRVhER1NOo64jFQesXkiNXW8/edit?ts=5dd2108c#)
- Fixes #166
> Add KubeCon19 banner

- index.html
@evilnick, all, please review, merge this PR and update the site before the US wakes up. We have people at KubeCon trying these instructions and fail. 
Changes on this PR:
- multipass creates VM with enough RAM and disk (thanks @kwmonroe)
- we use `multipass shell` to enter the VM. This shows better than the `multipass exec` 
- we do a `microk8s.status --wait-ready` to wait for MicroK8s to start
- do not suggest installing snapd in VMs, it is already there
- do not do `microk8s.start` since it has already started
- remove the `[...]` from the list of addons
- `microk8s.enable dns` and not istio. istio is not a standard service and it also takes along time to setup so it is not a good example for a quick start.
> Multipass exec mk8s

- docs/setting-snap-channel.md
Point users to the location on refresh scheduling rather than the generic options setting.
> Pointing to the right refresh scheduling location

- index.html
Removed the kubcon19 notice from the homepage
- Look at http://0.0.0.0:8027/
- See that the notice has been removed
> Remove kubecon notice

- docs/index.md
- Go to `/docs` and make sure the alias has correct spelling kubectl='microk8s.kube**ctl**'
Fixes #177
> Update misspelled word in docs

- index.html
- js/installversion.js
- Remove the external icon when setting the href of the download button
- Fix the layout when JS is not available
- Open the Windows and macOS tabs/boxes
- See that the download button does not have an external icon
- Switch JS off and refresh the page
- See that the get started section is now useable
> Make the version selector great again

- docs/addon-dashboard.md
Named link references were broken due to a simple whitespace parsing issue
> Fix named links on Dashboard Addon page

- docs/addons.md
Extend these docs to include Cilium with a link to the Cilium intro documentation.
> Add Cilium to docs

- _layouts/docs.html
Fix the copy functionality in the docs
- Go to /docs
- Click one of the copy to clipboard buttons
- Check it works
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/197
> Fix the copy functionality in the docs

- docs/install-alternatives.md
As noted in https://github.com/ubuntu/microk8s/issues/880 the boot arguments changed place in more recent RPi versions.
> RPi boot arguments

- docs/addon-dashboard.md
Without this, the URL works like a link but just reloads the page when clicked. (`href=""`)
> Fix URL in addon-dashboard.md

- _layouts/docs.html
- docs/install-proxy.md
This has come up a lot of times in the issues (most recently in https://github.com/ubuntu/microk8s/issues/917).
I added the proxy setup as part of the installation process instead of the configuration because if the proxy is not set you see immediately the system is not running correctly. Your thoughts on that @evilnick?
> Adding a proxy installation/configuration page

- _layouts/docs.html
- index.html
- Added a jekyll variable for the year in the footer's copyright
- ./run the site
- See the footer says 2020
Fixes #212
> Add a variable for the date in the footer's copyright

- index.html
Removing " Distribution of" from "Charmed Distribution of Kubernetes"
[List of work items including drive-bys]
- Compare it against the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit?ts=5e32f329) and accepts correct changes.
> Copy change on microk8s.io

- docs/troubleshooting.md
Add troubleshooting notes about the following issues:
- Microk8s will not work if the user's homedir is not under /home
- Microk8s will not work if the user's homedir is on NFS
- Microk8s will not work if the user uses ZFS
These are likely to be common situations for Microk8s users, and Microk8s
doesn't (or is unable to) detect or handle them, so they should be doc'd.
cf. https://github.com/ubuntu/microk8s/issues/401#issuecomment-579646285
> Update troubleshooting.md to note ZFS, NFS, snapd issues

- index.html
- Removed the 'BETA' label on the Clustering feature
- Compare to and update the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit)
Fixes #231
> Remove beta label from Clustering

- docs/index.md
This PR adds an additional command in the "Quick Start" guide: `sudo chown -f -R $USER ~/.kube`. This command is needed because if the user had ever run a `microk8s.kubectl` command with `sudo` the `~/.kube` directory would have been created with `root:root` permissions. As soon as the user enters the `microk8s` group she would be able to run the `microk8s.*` commands but the commands would be blocked from accessing `~/.kube` directory. The effect of this block is `microk8s.kubectl` taking minutes to complete. See for example the issue [0]. 
Note, with PR [1] we also prompt the user to gain access to the `~/.kube` directory in addition to adding himself to the microk8s group.
[0] https://github.com/ubuntu/microk8s/issues/1023
[1] https://github.com/ubuntu/microk8s/pull/1027
- Check out …
> Ask users to gain access to ~/.kube dir

- index.html
removed class causing download to get rewritten. 
- check link works
Fixes #241
> remove js class rewriting download link

- docs/install-alternatives.md
- index.html
- Revert to Multipass for Windows on Index page
- Revert to Multipass for macOS on index page
- revert to Multipass for alternative-install page in docs
> revert install instructions for macOS/Windows

- renovate.json
Disable renovate to avoid upgrades to ruby 2.7.
> Disable renovate for ruby

- templates/partial/_navigation.html
Update the text in the tweet button
- Click the tweet button and see that it is pre-populated with the following text:
- #microk8s is the easiest way to Kubernetes. Learn more at microk8s.io
(note that microk8s.io will be replaced with the URL of the site/demo link)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/2759
> Update tweet text in twitter button

- docs/addon-dashboard.md
If the user created the VM following the guide in https://microk8s.io/ for Windows, the name of the VM will be microk8s-vm
[List of work items including drive-bys]
Fixes #
> VM in windows like https://microk8s.io/

- templates/index.html
Cram more above the fold
- See that there is more above the fold
Fixes #
> Tighten fold area

- .gitignore
- redirects.yaml
From there it should be proxied to
https://github.com/ubuntu/microk8s/releases/download/installer-v2.0.0/microk8s-installer.exe
For https://github.com/canonical-web-and-design/microk8s.io/issues/280.
Twinned with https://github.com/canonical-web-and-design/deployment-configs/pull/382
QA
--
```
./run
```
Go to http://localhost:8027/install.txt, end up at http://localhost:8027/install/v2.0.0.txt
> Redirect /install.exe to /install/v2.0.0.exe

- templates/partial/_navigation.html
There's a MicroK8s category now, instead of just a tag. All of the tagged items were moved to the category.
> Update Discourse link

- requirements.txt
- templates/contact-us.html
- webapp/app.py
- Use discuss.kubernetes.io for microk8s docs: https://discuss.kubernetes.io/c/microk8s/26
- View the site locally in your web browser at: http://0.0.0.0:8027/docs
- Check that the docs work well
> Update discourse URL to use discuss.kubernetes.io

- redirects.yaml
- templates/partial/_get-started-windows.html
- created a redirect for the Windows download and linked to that from the instructions
- Select the Windows instructions and click on the Download button, see that it points to a local file and appears to download from there
Fixes #280
> Redirect for windows installer

- .github/workflows/pr.yml
- templates/index.html
- Remove datasheet from banner
- See the datasheet link has been removed per the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit?ts=5f609168)
Fixes #318
> Remove datasheet from banner

- .webpack/entry.js
- package.json
- static/js/cookie-policy.js
- static/sass/styles.scss
- templates/base_layout.html
- templates/partial/_footer.html
- yarn.lock
- Add the new cookie module to the site
- View the site locally in your web browser at: http://0.0.0.0:8027
- See the new cookie popup and try the settings
- Test the "Manage your tracker settings" link from the footer
Fixes #333
> Add new cookie policy

- templates/docs/document.html
Fix the template variable used for page title
- View the site locally in your web browser at: http://0.0.0.0:8027/docs
- Click through the pages and check the page title reflects the content
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/352
> Set the title of the docs pages

- requirements.txt
- webapp/app.py
Upgrade the discourse package to the latest 2.1.0
- View the site locally in your web browser at: http://0.0.0.0:8027/docs
- See that the docs are rendered correctly
> Upgrade the discourse package to the latest 2.1.0

- konf/site.yaml
This PR is similar to https://github.com/canonical-web-and-design/ubuntu.com/pull/8907
After updating the Konf snap with https://github.com/canonical-web-and-design/konf/pull/5 , we need to use `^~` for the location blocks on Nginx
- Added `^~` for Nginx proxy locations
- Deploy the current configuration to microk8s
- Modify your `/etc/hosts/` file
- Try to download microk8s from the website, it should work.
> Added ^~ for nginx proxy locations

- redirects.yaml
Update the redirect file to point to the latest installer binary
> Update redirects.yaml for new windows installer

- static/sass/styles.scss
- templates/base_layout.html
- templates/index.html
- Fix bug install instructions visible for a second on page load
- View page at: https://microk8s-io-379.demos.haus
- Comapre to https://microk8s.io/ where on refresh install instructions are visible for a second.
- Check toggling JS on and off, instructions should be visible with JS disabled and not visible until selected when JS is endabled
Fixes #377
> Hide install instructions on page load

- .github/workflows/docs-links.yaml
some suggested filters for the linkchecker
127.0.0.1 addresses are obviously always referring to the user localhost and should be skipped (this should probably be on all the link checkers)
*.xip.io addresses are a special domain used by MicroK8s authentication
Feel free to rewrite the regex to improve it
> update docs link-checker

- .github/workflows/docs-links.yaml
change linkchecker arguments to also filter .nip.io addresses (used for dns internally in microK8s)
The only remaining errors showing on this are the result of mistaken redirects ( should be fixed by [this PR](https://github.com/canonical-web-and-design/canonicalwebteam.discourse/pull/102))
> linkchecker update

- templates/index.html
Added CTA button to landing site and updated copy on end of page 
- View page at: https://microk8s-io-439.demos.haus
- Copydoc: https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.pt6iw0mepowo
- Button should lead to https://microk8s.io/contact-us
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4404
> Added cta button on landing page

- templates/404.html
- templates/500.html
- templates/base_layout.html
- templates/features/high-availability.html
- templates/index.html
- templates/thank-you.html
- templates/tutorials/index.html
Add dynamic copy doc links to the head of each page
- Go to pages in the demo and check the correct copy doc is linked
- Check the copy docs links against the pages here: https://drive.google.com/drive/folders/1p6lHFpMFXFeSmVUx3Hyw-zlySn8MZHpP
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/455
> Add dynamic copy doc links to the head of each page

- templates/tutorials/index.html
- Added "Installing MicroK8s on Apple M1 silicon" tutorial to /tutorials
- Created related issue to fetch tutorials dynamically: https://github.com/canonical-web-and-design/microk8s.io/issues/460
- View the demo in your web browser at: https://microk8s-io-459.demos.haus7/tutorials
- See that "Installing MicroK8s on Apple M1 silicon" is the first tutorial there, and that it links to the right tutorial on ubuntu.com
> Add new microk8s tutorial

- templates/tutorials/index.html
- Moved latest tutorial to the bottom of the list, as [requested](https://docs.google.com/document/d/1Lpo7Od9VA1aHYmr9UVp02vCGOP5Zxmzx4zZE9YJwlQg/edit?disco=AAAAS_5CocE)
- View the demo in your web browser at: https://microk8s-io-461.demos.haus/tutorials
- See that "Installing MicroK8s on Apple M1 silicon" is the last listed tutorial
> Move M1 tutorial to bottom of the tutorial list

- templates/compare/index.html
- Changed "ARMh" to "ARMhf", as pointed out in the [copy doc](https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo/edit?disco=AAAAUFcgKWQ)
- View the site locally in your web browser at: http://0.0.0.0:8027/compare
- See that "ARMhf" appears in the "Architecture support" row of the table, not "ARMh"
> Fix "ARMhf" typo on /compare

- templates/compare/index.html
Removes the `mobile-card` class from the 'compare' table. The table is still readable without a mobile class.
- View the site locally in your web browser at: https://microk8s-io-509.demos.haus/compare
- Check the table is readable on different screen sizes.
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/506
> Make compare table responsive

- templates/tutorials/index.html
- Add one tutorial on the `/tutorials` page
- Update `p-heading--four` to `p-heading--4`
- Compare page against [copy doc](https://docs.google.com/document/d/1Lpo7Od9VA1aHYmr9UVp02vCGOP5Zxmzx4zZE9YJwlQg/edit)
- Demo at https://microk8s-io-523.demos.haus/tutorials
Fixes [#5032](https://github.com/canonical-web-and-design/web-squad/issues/5032)
> Copy update on /tutorials

- templates/index.html
- Fixed typo: "develoeprs" to "developers"
- See that the change has been made
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/525
> Fix typo on index

- templates/docs/document.html
- Added expandable side navigation
- View the site locally in your web browser at: https://microk8s-io-549.demos.haus/docs
- Click on "Alternative install methods" on the side nav (currently the only nav item with children)
- See that it expands as expected and that the child links also behave as expected 
- Click on any other side nav link and see that "Alternative install methods" collapses 
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/538
> Expandable side navigation

- static/sass/styles.scss
- templates/index.html
- templates/partial/_get-started-linux.html
- Addressed the following from [this list](https://github.com/canonical/microk8s.io/pull/608#issuecomment-1698781842):
- Fixed inline GH icons on mobile screens
- Fixed heading bottom spacing
- Updated Linux logo
- Switched to breaking spaces at bottom CTA 
- View the site locally in your web browser at: https://microk8s-io-617.demos.haus/
- See that the requested changes have been made
> Apply final review suggestions

- requirements.txt
Bump canonicalwebteam.discourse to 5.4.9
- Trying to access <http://127.0.0.1:8027/docs/command-reference>, an internal error was thrown:
```bash
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File …
```
> Bump canonicalwebteam.discourse from 5.4.3 to 5.4.9

- templates/features/high-availability.html
- Added missing href
- View the site locally in your web browser at: https://microk8s-io-650.demos.haus/features#high-availability 
- Click on the "Learn more about how HA microk8s works" link and see that you're routed correctly as per [doc](https://docs.google.com/document/d/1G6FijpahZCSfxcuFAkv22wKCILEkF2u4Q0TQUfkW5i4/edit)
Reported on [MM](https://chat.canonical.com/canonical/pl/csejuqo6ktf3pkpwkwt1m6h9nr)
> Fix /features link

- package.json
- requirements.txt
- templates/resources/videos-and-webinars.html
- webapp/app.py
- yarn.lock
- Upgrade canonicalwebteam.search to 2.1.1
- Upgrade canonicalwebteam.flask-base to 2.0.0
- Pass `app` to `build_search_view()`
- Bump vanilla-framework to 4.16.0
- Add `p-rule` class to `<hr>`s
- Go to https://microk8s-io-661.demos.haus/docs/search
- Search something
- See rate limit is hit (currently set to 1, so you can search 1 time before hitting it)
Fixes https://warthogs.atlassian.net/browse/WD-15015
> Upgrade canonicalwebteam.search to 2.1.1

- templates/docs/document.html
- Include h3 headings to table of contents (displayed on the right side of the page). H3 contents should nest their parent H2 headings.
- Go to https://microk8s-io-664.demos.haus/docs/configure-host-interfaces
- Check that the table of contents on the right side of the page load as expected
- It should catch h2 and h3 headings. H3 headings should nest their corresponding H2 parent headings.
Fixes #[17308](https://warthogs.atlassian.net/browse/WD-17308)
> WD-17308 Include H3 in docs TOC

- templates/isv/contact-us.html
- Company and Job title fields are now mandatory
- drive by: added "is-required" class to other labels with input's marked as required
- View the site in your web browser at: https://microk8s-io-666.demos.haus/isv/contact-us
- Verify the company and job title fields are mandatory
Bonus points: try to submit the form to make sure it works.
Fixes #[WD-19677](https://warthogs.atlassian.net/browse/WD-19677)
[WD-19677]: https://warthogs.atlassian.net/browse/WD-19677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mandatory company and job title fields on microk8s.io contact form

- templates/features/high-availability.html
- removed unavailable youtube video from "High Availability" section
- View the site in your web browser at: https://microk8s-io-668.demos.haus/features
- Verify the unavailable youtube video is removed from "High Availability" section
Fixes #[WD-21210](https://warthogs.atlassian.net/browse/WD-21210)
[WD-21210]: https://warthogs.atlassian.net/browse/WD-21210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WD-21210] removed unavailable media

- templates/index.html
Fix broken webinar link
- Check out [demo link](https://microk8s-io-671.demos.haus/)
- Ensure that clicking `Watch the webinar: K8s at the edge: easy as “Pi”` takes you to the correct page
Fixes #[22343](https://warthogs.atlassian.net/browse/WD-22343)
> Update `K8s at the edge: easy as “Pi”` webinar link URL
