Dockerfile
'cos it's newer, better, and only 82.4MB.
QA
--
``` bash
docker build --tag microk8s.io --build-arg COMMIT_ID=`git rev-parse HEAD` .
docker run -ti -p 8927:80 microk8s.io
```
Now go to http://127.0.0.1:8927 and see the site running.
=> Base production image off bionic

index.html
=> add relevant google tag

_sass/styles.scss, index.html
Created new index page with Microk8s from  [the copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#) and [design spec](https://github.com/ubuntudesign/web-squad/issues/915)
- Run the site using the command `./run`
- View the site locally in your web browser at: [http://0.0.0.0:8027/](http://0.0.0.0:8027/)
- Run through the following [QA steps](https://github.com/canonical-webteam/practices/blob/master/workflow/qa-steps.md)
- Make sure the MicroK8s matches the  [the copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#) and [design spec](https://github.com/ubuntudesign/web-squad/issues/915
Fixes https://github.com/canonical-websites/microk8s.io/issues/25
=> Microk8s homepage refresh 19

_sass/styles.scss, index.html
- Increase contrast of the menu links on small screens
- Add title to iframes 
- Form elements do not have associated labels 
Check the things are done
=> Accessibiliy fixes

_layouts/base.html, index.html
Validated the homepage using https://validator.w3.org/nu/#textarea. Also, updated the report a bug link in the footer.
- Copy the source code of the homepage
- Run it by https://validator.w3.org/nu/#textarea
- Check its green and the footer link is correct
=> Validated the homepage

_layouts/base.html, _sass/_sidebar.scss
Added a highlight to the navigation when in the docs section
- Go to docs
- See the nav item is selected
Fixes #43
=> Highlight docs when in docs

docs/dockerd.md, docs/index.md, docs/registry.md
Convert the links in the docs pages to real links
Click through the docs and check there are no hardcoded links
Fixes https://github.com/canonical-websites/microk8s.io/issues/44
=> Convert the links in the docs to true links

index.html
- Check that the button in the hero strip has vertically centred text
=> Update snap store button image

index.html
=> Surely we should link to /docs?

docs/index.md
This is in response to https://github.com/ubuntu/microk8s/issues/221
=> Document upstream dns updates

docs/release-channels.md
The snap refresh command is wrong. Fixes: https://github.com/ubuntu/microk8s/issues/231
=> Fix the snap refresh command

index.html
- Updated the homepage with edits on the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit?ts=5c3677ff#)
- download the branch
- run the site
- look at the [homepage](http://0.0.0.0:8027)
- qa it like normal
- see that the text is like the copy doc
Fixes #54
=> Update homepage with a user quote

docs/index.md, docs/ports.md, docs/registry.md
Some links were broken. Also the reference sections had the URLs text.
Fixes: https://github.com/canonical-websites/microk8s.io/issues/71
=> Fix broken links

index.html
Change kubernetes image to retina
Go to [http://0.0.0.0:8027/](http://0.0.0.0:8027/) and make sure the kubernetes image is retina quality.
Fixes #66
=> Change kubernetes logo to retina

index.html
1. Pull the branch or open the demo service
2. Visit the homepage and notice the image from the Snap Store badge pointing to `https://snapcraft.io/static/images/badges/en/snap-store-white.svg`
3. #winning
=> Updated snap store badge

docs/index.md, docs/release-channels.md
Update the release channels docs section to include discussion on pre-stable releases.
=> Channels update - pre-stable

docs/working.md
These tables do not look nice so I removed a column with some insignificant info.
=> Remove table columns in docs to make them look nice

docs/index.md
=> Doc updates to reflect changes that came with v1.15

_layouts/base.html
* Google Optimize snippet to enable A/B tests
* Ensure Google Optimize reports the demo site as enabled (:+1: )
=> Added Google Optimize

index.html
- Update "Features" to match copy doc
- View the site locally in your web browser at: [http://0.0.0.0:8027](http://0.0.0.0:8027)
- Compare to [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.5jnq0eog0tmw)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/5624
=> Update "Features" to match copy doc

_layouts/base.html, _layouts/docs.html, _sass/_docs.scss, _sass/styles.scss, index.html, package.json, yarn.lock
Fix the copyable code patterns
Remove cssnano
Applied the new docs layout styling
Fixed the footer styling
Update the year in the footer
- Run `./run clean`
- Run `./run`
- Check it all builds with no errors
- Go to http://0.0.0.0:8027/
- Check the header logo on hover stays white
- Check the code snippets are copyable
- Check the footer looks ok and has the correct year
- Go to docs and check they all look good
- Check the docs footer has the correct year
=> Fix the copyable code patterns

_sass/styles.scss, index.html
- Updated the microk8s.io homepage
- Look at the homepage - http://0.0.0.0:8027/
- Compare it to the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
=> Update microk8s.io homepage

index.html
- Added link to Hightower quote and Multipass
- top aligned the two quotes
- See the change match the comments in the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit) and accept the changes if ok
=> Minor layout updates and added two links

index.html
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/104
Copy doc: https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.wka86qz6snk0
=> Update index page title

docs/ports.md
This is more affirmative than the previous version and more clear on what is used and how.
=> Services and auth rework

index.html
## Done
- Optimised "Certified Kubernetes" SVG
## QA
- Visit https://microk8s.io/
- Open dev tools, check size of `96d35aa4-certified-kubernetes-logo.svg` is around 46kb
- Visit http://0.0.0.0:8027/
- Open dev tools, check size of `4b663a6c-certified-kubernetes-logo.svg` is around 16kb
=> use optimised "certified kubernetes" SVG

docs/working.md
This was reported by our users in https://github.com/ubuntu/microk8s/issues/704
Fixes: https://github.com/ubuntu/microk8s/issues/707
=> Add never pull image when working without registry

docs/index.md
This is more of a test than anything else (I've been away for a while) but I do find the opening line a little jarring. Its style is more akin to a marketing shoutout.
=> suggested wording

_layouts/docs.html, docs/commands.md
=> Add command reference

_layouts/docs.html, docs/configuring-services.md
This adds some detail on the services running, with (updated) links to component docs
=> [Docs] Adds pages for configuring the systemd services run by MicroK8s

docs/index.md
We started shipping flannel as our CNI.
=> Remove mentioning of kubenet

docs/ports.md
=> Fix path to certs

_layouts/docs.html, docs/install-alternatives.md
When we fix up the navigation (when the other pages are landed) I think we will have individual entries for Windows, macOS etc, but for now we can make do with one link.
=> [Docs] Add alternative install page

_layouts/docs.html, docs/get-in-touch.md
Adds a section for contributing to microk8s
=> [Docs] Add contributing section

docs/ports.md
update credentials file location
Fixes #155
=> [Docs] Update file location in ports.md

docs/addons.md
Add link to metallb from the metallb addon
=> Adding MetalLB addon

docs/index.md, docs/install-alternatives.md
Fixes to Multipass page (also adds link back to quickstart, Fixes #170 @kwmonroe )
Add note about aliases (Fixes #172)
=> Tweaks to quick start/multipass

docs/addon-dashboard.md
Main issue we address here is the accessing the dashboard when MicroK8s is in a VM.
Fixes: https://github.com/canonical-web-and-design/microk8s.io/issues/181
Fixes: https://github.com/canonical-web-and-design/microk8s.io/issues/159
Fixes: https://github.com/ubuntu/microk8s/issues/771
=> Update dashboard docs for in-VM setups

docs/install-alternatives.md
=> “VirtulBox” > “VirtualBox”

docs/commands.md
Updating doc to reflect new "microk8s.status" output
=> Updating commands.md

docs/addons.md
Resolves https://github.com/ubuntu/microk8s/issues/908
=> Note: metallb does not work with multipass on macOS

docs/index.md, docs/install-alternatives.md, docs/setting-snap-channel.md
fixed various refs to indicate 1.17 is current release
=> update current version refs to 1.17

docs/troubleshooting.md
=> Add missing </p> to troubleshooting.md

package.json
Update the global nav.
- check the demo works
- global nav looks ok
=> Update global nav

docs/addon-fluentd.md
A simple update of an incorrect command.
=> Updates fluentd addon with proper enable command.

.dockerignore, Dockerfile, nginx.conf
Multistage builds to decrease image size, faster image building.
- `export DOCKER_BUILDKIT=1`
- Build image with new dockerfile `docker build --tag myimage --build-arg BUILD_ID=myfakeid .`
- Run conainter with this image `docker run -ti -p 8111:80 myimage`
- Check build_id `myfakeid` is present `curl localhost:8111`
Fixes #123
=> Multistage builds

_layouts/base.html
Add copy-doc plugin meta
- Check that the meta is in the code and the link is correct
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/226
=> Add copy-doc plugin meta

docs/addon-dashboard.md, docs/addon-dns.md, docs/addon-fluentd.md, docs/addon-gpu.md, docs/addon-linkerd.md, docs/addons.md, docs/clustering.md, docs/commands.md, docs/index.md, docs/install-alternatives.md, docs/install-proxy.md, docs/ports.md, docs/registry-built-in.md, docs/registry-images.md, docs/registry-private.md, docs/registry-public.md, docs/release-notes.md, docs/troubleshooting.md, index.html
=> 1.18 Release

docs/install-alternatives.md, docs/release-notes.md, index.html
=> Brew update

index.html, js/copytoclipboard.js, js/installversion.js, js/tabs.js
Update text and add back missing js files
- Compare to the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/7115
=> Update text and add back missing js files

docs/clustering.md
=> docs(clustering): Formatting of bash commands

docs/addon-dashboard.md, docs/uninstall-alternatives.md
@evilnick please have a look over and let me know your thoughts.  
I added the file for uninstall, but no idea where it should go.
On top of this, we need to say, on the Windows install section; "HyperV must be enabled to install MicroK8s (https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v)".  I'd add this, but I don't want to mess your stash with the installer docs.
=> Adding installer docs for dashboard

docs/ports.md
Updated docs to explain remote access setup, after this discussion: 
https://github.com/ubuntu/microk8s/issues/849
Fixes #849
=> Remote access explanation

docs/commands.md
=> Update the arguments of add-node and status commands

templates/index.html
remove extraneous code
Fixes #288
=> fix unexpected item in text area

.eslintrc.js, .github/workflows/pr.yml, .webpack/entry.js, .webpack/rules.js, package.json, static/js/sample.test.js, webpack.config.js, yarn.lock
- Update webpack config it is inline with other projects
- Add codecov for JS files
- Run the site using the command `./run serve` or `dotrun`
- Check that there is a `static/js/dist` directory which contains all the built JS files
- Check that the following commands work as expected:
- `dotrun exec yarn lint-js`
- `dotrun exec yarn test-js`
- `dotrun exec yarn build-js`
- `dotrun exec yarn watch-js`
=> Update webpack config

templates/index.html
- Replaced second pull quote
- Compare to the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit?ts=5ee24485#heading=h.se23hc9mrdip)
=> Replace quote

requirements.txt
Fixes #300
QA
--
Go to https://microk8s-io-302.demos.haus/docs/addon-ambassador, check it works.
=> Use discourse-docs v1.0.1

templates/partial/_get-started-windows.html
Fix "Join the community" URL
- Use the demo link and follow the instructions in the issue #312 
Fixes #312
=> Update 'Join the community' url

templates/index.html
Update the site content
- Check the content matches [the copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
- Check the design looks ok
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/311
=> Update the site content

templates/base_layout.html, templates/index.html
- Rebuild microk8s.io based on copy doc 
- Check page matches [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
- Check design 
Fixes [#3259](https://github.com/canonical-web-and-design/web-squad/issues/3259)
=> Rebuild microk8s home page

templates/features/features_layout.html
- Remove topped suru hero on `/high-availability`
- View the site locally in your web browser at: http://0.0.0.0:8027/high-availability and check design
=> Remove suru hero

templates/index.html
- Update video on hero section index.html
- Check video in hero section is correct from [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit)
Fixes [#8477](https://github.com/canonical-web-and-design/ubuntu.com/issues/8477)
=> Update video hero section

templates/tutorials/index.html
* Fixed #348
* Reduced difficulty ratings from 3 to 1 for intro tutorials
- Ensure easy tutorials look easy
=> Update tutorials difficulty ratings and fix typo

templates/index.html
- Update content to match page content
- Update video to a youtube embed
- Check the copy matches the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.8udxsgb0okfj)
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/358
=> Update the homepage content

requirements.txt
Revert the discourse upgrade
- Check out the demo
- Go to docs and see there is a sidenav
=> Revert the discourse upgrade

package.json, webpack.config.js, yarn.lock
Remove Tenser and Husky as dependencies
- Check the demo looks the same as live
- Check the main.js is minified still
=> Remove Tenser and Husky as dependencies

requirements.txt
Reverts canonical-web-and-design/microk8s.io#403
=> Revert "Update dependency canonicalwebteam.discourse to v4"

requirements.txt, templates/docs/document.html, webapp/app.py
Discourse docs v4.0.2
- make sure `/docs` work
=> Discourse docs v4.0.2

webapp/app.py
- Revert back to the original doc topic
- Check https://microk8s-io-414.demos.haus/docs is working
=> Revert back to the original doc topic

templates/index.html
Changed "subscription" to "license" as per the copy doc https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.ku44g3w19nls
- Check off the comment in the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.ku44g3w19nls) if correct 
Fixes #9801
=> Copy update; Changed "subscription" to "license"

templates/index.html
Changed to "no license fee"
- Check changes against the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.pd8kwv4tyu4y) and accept correct ones.
Fixes #9881
=> Minor copy update

templates/tutorials/index.html
Add new Gitlab tutorial 
- https://microk8s-io-423.demos.haus/tutorials Added new tutorial according to [copy doc](https://docs.google.com/document/d/1Lpo7Od9VA1aHYmr9UVp02vCGOP5Zxmzx4zZE9YJwlQg/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4175
=> Add Gitlab tutorial

templates/sitemap/sitemap-index.xml, templates/sitemap/sitemap-links.xml, webapp/app.py
- Add sitemaps to microk8s.io
- Run the site using the command `dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8027/sitemap.xml
- Remove the anbox-cloud URL and replace with the demo/localhost link
- Make sure they work
Fixes #
=> Add sitemaps to microk8s

templates/contact-us.html
- Updated form on `/contact-us`
- copydoc: https://docs.google.com/document/d/1KkLHMrGipY4zgIXreujpyJlLvYUs-iAlP-FtpYrZmWA/edit#
- Run the site using the command ./run serve or dotrun
- View the site locally in your web browser at: http://0.0.0.0:8027/contact-us
- Try to submit without filling out all relevant fields, check that it correctly fails
- Do the same but with all fields filled and submit
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4428
=> Updated contact-us form

redirects.yaml
Points at the latest MicroK8s Windows installer exe.
=> v2.2.0 release

templates/index.html
- Updated the content of the page https://microk8s.io/ to match the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
- Go to the website https://microk8s-io-444.demos.haus/
- Make sure that the newly added section matches the [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#)
Fixes https://github.com/canonical-web-and-design/ubuntu.com/issues/10485
=> Updated the page /index.html

redirects.yaml
cc @evilnick @ktsakalozos
v2.2.1 has been released so point to this.
=> Installer v2.2.1 release

templates/docs/document.html
- Fix hidden elements
- Check there are no separators on the side navigation https://microk8s-io-462.demos.haus/docs
=> Fix hidden elements

scripts/linkcheckerrc
Add localhost links to link ignore
- Check code looks good
=> Add localhost links to link ignore

templates/index.html
Fix embedded video's 404 error
- Please check if the video displays on the page and is responsive and plays well. 
Fixes #465
=> Fix embeded video

templates/compare/index.html, templates/partial/_navigation.html, webapp/app.py
Build `/compare` page
- Please check page against [copy doc](https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo/edit)
Fixes [#4649](https://github.com/canonical-web-and-design/web-squad/issues/4649)
=> Build /compare page

templates/contact-us.html
- Post forms to https://ubuntu.com/marketo/submit
- Decapitalise input names
- Update hidden inputs
- Remove recaptcha
1. Go to  https://microk8s-io-497.demos.haus/contact-us
2. Fill in the form and submit it
3. Check the form is submitted and redirects to a thank you page on microk8s.io
4. Check the submitted data is on the list in marketo (form ID is 3230)
Fixes #496
=> Update marketo endpoint

templates/isv.html, webapp/app.py
*The contact us form will be created in a separate issue so we can get this page out now*
- Build ISV campaign page as per [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)
- View the site locally in your web browser at: https://microk8s-io-513.demos.haus/isv
- Compare against [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)
Fixes https://github.com/canonical-web-and-design/master-epics/issues/408
=> Build ISV campaign page

templates/isv/contact-us.html, templates/isv/index.html, webapp/app.py
- Create /isv contact-us form [copydoc](https://docs.google.com/document/d/1zFVotFVMovmyx-Csqv_OEoB4uNMp69xOGi1WjENIU7A/edit)
- Update copy as per [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)
- Go to /isv compare against [copydoc](https://docs.google.com/document/d/1pcUx3oJ4ZcgRG6nGv6kzHSf9tFZZnaTK1jzecKFZxGo/edit#)
- Check the contact form opens and matches the [copydoc](https://docs.google.com/document/d/1zFVotFVMovmyx-Csqv_OEoB4uNMp69xOGi1WjENIU7A/edit)
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5005
=> Create /isv contact-us form

templates/isv/contact-us.html
Updates the form-id, see [copydoc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit)
- Check the formid in the doc matches the one used in the form
=> Update form-id for /isv contact-us form

templates/index.html
- Updated page as per [copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit#heading=h.1pwn63px8lmw)
- Check against doc and see that all changes have been made
- Test links
Fixes https://github.com/canonical-web-and-design/web-squad/issues/4996
=> Update index page according to doc

templates/resources/index.html
- Change embedded video to screenshot from slide 3 of linked deck
- Update href
- Originally requested via [doc](https://docs.google.com/document/d/1PB5-CamGmSjhbuyuGSariC9zUW-8krAJD0l8JyvNk20/edit#)
- View the site locally in your web browser at: https://microk8s-io-527.demos.haus/resources
- See that the change has been made and that it links to the correct blog
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5127
=> Update asset on /resources

templates/index.html
=> Add link to addon howto

templates/index.html
Copy updates
- Check https://microk8s-io-531.demos.haus/ against [copy docs](https://github.com/canonical-web-and-design/web-squad/issues/5219)
- Check the video on https://microk8s-io-531.demos.haus/
Fixes https://github.com/canonical-web-and-design/web-squad/issues/5219
=> Copy updates on homepage

templates/compare/index.html
- Updated table as per [copy doc](https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo/edit)
- View the site locally in your web browser at: https://microk8s-io-535.demos.haus/compare
- See that requested changes have been made
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/534
=> Update table copy on /compare

templates/compare/index.html
added POWER9 to table
Fixes #551
=> add POWER9

package.json, templates/docs/document.html, yarn.lock
Updates to vanilla 3.7.1 & updates side navigation to be compatible with 3.7.1
- Go to https://microk8s-io-554.demos.haus/docs# and check the side navigation has expandable child elements and works as expected.
Fixes https://github.com/canonical/microk8s.io/issues/553
=> Update to vanilla 3.7.1 & update side navigation

redirects.yaml
[List of work items including drive-bys]
Update installer redirect to fetch latest version from GitHub.
Fixes #
=> Update installer to 2.3.1 (microk8s 1.26)

templates/compare/index.html
- Update logos on /compare
- Minor fly-by's
- Go to https://microk8s-io-590.demos.haus/compare and check that the logo matches that from [the issue](https://warthogs.atlassian.net/browse/WD-1758)
Fixes https://warthogs.atlassian.net/browse/WD-1758
=> Update logos on /compare

redirects.yaml
[List of work items including drive-bys]
Fixes #
=> update installer to 2.3.2

.stylelintrc, package.json, static/sass/_pattern_tutorials.scss, templates/base_layout.html, templates/tutorials/index.html, yarn.lock
- Upgraded site to latest Vanilla version
- Applied redesign as per [doc](https://docs.google.com/document/d/1Lpo7Od9VA1aHYmr9UVp02vCGOP5Zxmzx4zZE9YJwlQg/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?type=design&node-id=94%3A4183&mode=design&t=04EfFbvHoCVgWIP2-1)
- View the site locally in your web browser at: https://microk8s-io-606.demos.haus/tutorials
- Check page against doc and design
Fixes https://warthogs.atlassian.net/browse/WD-4188
=> Apply redesign /tutorials

templates/404.html, templates/500.html, templates/partial/_error.tmpl
- Updated error pages as per [Jira ticket instructions](https://warthogs.atlassian.net/browse/WD-5793?focusedCommentId=296299). These are supposed to match the error pages on c.com, both in copy and design 
- View the site locally in your web browser at: https://microk8s-io-612.demos.haus/not-real-url
- See that the error page shows up correctly
Fixes https://warthogs.atlassian.net/browse/WD-5793
=> Apply redesign to error pages

static/js/tabbed-content.js, static/sass/styles.scss, templates/index.html, templates/partial/_get-started-linux.html, templates/partial/_get-started-macos.html, templates/partial/_get-started-windows.html, templates/partial/_github-buttons.html
- Applied redesign as per [doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?node-id=0%3A1&mode=dev)
**NOTE: Nav bar and footer to be updated in coming PR**
- View the site locally in your web browser at: https://microk8s-io-610.demos.haus/
- Check against doc and design
Fixes https://warthogs.atlassian.net/browse/WD-3755
=> Apply landing page redesign

static/sass/styles.scss, templates/contact-us.html
- Applied redesign as per [doc](https://docs.google.com/document/d/1KkLHMrGipY4zgIXreujpyJlLvYUs-iAlP-FtpYrZmWA/edit) and [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io?node-id=407%3A6063&mode=dev)
- View the site locally in your web browser at: https://microk8s-io-611.demos.haus/contact-us
- Check against doc and design
Fixes https://warthogs.atlassian.net/browse/WD-4196
=> Apply /contact-us redesign

templates/docs/document.html
- Applied minor updates to align with new Vanilla
- View the site locally in your web browser at: https://microk8s-io-615.demos.haus/docs
- Check that functionality works as expected
Fixes https://warthogs.atlassian.net/browse/WD-4190
=> Apply /docs redesign

package.json, static/sass/_settings.scss, static/sass/styles.scss, templates/base_layout.html, templates/docs/document.html, templates/partial/_footer.html, templates/partial/_navigation.html, yarn.lock
Updates docs to use new layout from Vanilla 4.5.
- Review docs in new layout, make sure it works as expected
- https://microk8s-io-624.demos.haus/docs
=> Update to new documentation layout

redirects.yaml
Update microk8s-installer.exe redirect to [installer-v2.3.4](https://github.com/canonical/microk8s/releases/tag/installer-v2.3.4)
=> Update installer to 2.3.4

templates/resources/videos-and-webinars.html
- Embedded youtube and thumbnails where available 
- View the site locally in your web browser at: https://microk8s-io-625.demos.haus/resources
- Check that the black suru containers have been replaces with either thumbnails or embedded videos
Fixes # https://warthogs.atlassian.net/browse/WD-6355
=> /resources - Add thumbnails, embed videos

templates/thank-you.html
Refresh /thank-you page according to [design](https://www.figma.com/file/0DTIS3uNNUuDAdCKWrk8Uf/23.10---Microk8s.io-(rebranding)?type=design&node-id=1130-2835&mode=design&t=aRjwXXD09aetbgpj-4) and [copy doc](https://docs.google.com/document/d/1zAmRxMVFQhUPv9jBjVHJPnWfJMjiB78dQfY__h4pE7o/edit).
- Navigate to /thank-you page and check if it's implemented correctly according to the design and copy doc on all screen sizes.
Fixes https://warthogs.atlassian.net/browse/WD-5931
=> [WD-5931] rebrand /thank-you page

templates/index.html
Replace lightweight with effortless which matches the request in [the copy doc](https://docs.google.com/document/d/1ObWmhRc4GCIhrBi8gT7yIIs0J_dn_8ravfLtcwhr3uQ/edit).
=> Replace lightweight with effortless

templates/compare/index.html
- Applied copy update as per [doc](https://docs.google.com/document/d/1wWos3iWMTCqDbxZBDuSVqvY6ZwYux-goCrX0L0E5Weo/edit) 
- View the site locally in your web browser at: https://microk8s-io-644.demos.haus/compare
- See that the requested change was made
Fixes https://warthogs.atlassian.net/browse/WD-9563
=> Copy update /compare

templates/isv/contact-us.html
Remove sales numbers
- [demo link](https://microk8s-io-648.demos.haus/isv/contact-us)
- View the site on demo
- Run through the following [QA steps](https://discourse.canonical.com/t/qa-steps/152)
- Check that the sales numbers are removed
[WD-11393](https://warthogs.atlassian.net/browse/WD-11393)
[WD-11393]: https://warthogs.atlassian.net/browse/WD-11393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WD-11393 - remove sales numbers

.github/workflows/pr.yml, requirements.txt
- Update test-python to use ubuntu-latest
- Check the 'test-python' CI runs and passes
Fixes https://warthogs.atlassian.net/browse/WD-22658
=> Fix: Update test-python to use ubuntu-latest
